Boilerplate: Update to 4e45b07da020589cff099e6558a944c629ecc456 (#319)
Conventions:
- openshift/golang-lint: Update
- openshift/golang-codecov: Update
---
https://github.com/openshift/boilerplate/compare/58a2b753b72375be4493ab3d19452666509c61ed...4e45b07da020589cff099e6558a944c629ecc456

commit: bcb12262fe63fe08a30735ce4eed07bc9f17b196
author: Brady Pratt
pipelines/catalog-builder: runafter clone-repo

prefetch-dependencies task was dropped and this was missed

Signed-off-by: Brady Pratt <bpratt@redhat.com>

commit: 460d53cae97c845815372c807dcda2ba382089b1
author: Josh Branham
Add CLAUDE.md for AI development assistance

Add comprehensive documentation to help Claude Code understand the
boilerplate repository structure, architecture, and common development
workflows. This includes information about conventions, testing commands,
and integration points with Prow and Konflux.

🤖 Generated with [Claude Code](https://claude.ai/code)

Co-Authored-By: Claude <noreply@anthropic.com>

commit: 46f0a16acf7c5a3f2bcc332d329cbfdf4bf3f0b8
author: Josh Branham
Tweaks to Konflux release process in README

commit: 944a57d1a4c2f2354b5de93aa9e1745a6c9d1f7e
author: Brady Pratt
pipelines/catalog-builder: drop prefetch-dependencies

it shouldn't be needed since we are building the bundle (maybe bundler
though?)

```
Error: InvalidInput: 1 validation error for user input
packages -> 0
  Input tag 'true' found using 'type' does not match any of the expected tags: 'bundler', 'cargo', 'generic', 'gomod', 'npm', 'pip', 'rpm', 'yarn'
```

Signed-off-by: Brady Pratt <bpratt@redhat.com>

commit: 3e0327b0f032559c7b7584e0c261bcb0500850e3
author: Brady Pratt
pipelines/catalog-builder: drop SOURCE_ARTIFACT param

```
invalid result reference in pipeline task "fbc-fips-check": "SOURCE_ARTIFACT" is not a named result returned by pipeline task "prefetch-dependencies"
```

Signed-off-by: Brady Pratt <bpratt@redhat.com>

commit: 3727d019e928a40ce58809e4b3d823abc5d93e7f
author: Josh Branham
Ensure consumers FROM statements in Dockerfiles are using ubi9

commit: 8d710dd93c88aef42a94fa05836579b261419039
author: Josh Branham
Bump ubi image to 9 and go to 1.24

commit: 8526515e56663e00ff0efa011f022a7c0a8c6e13
author: Jonah Brawley
Consolidate other team members into 1 MR

commit: 24d195021cbd1fbbdf41556a6a77a2bde13598b6
author: Jonah Brawley
Update Owners Aliases for Team FedRAMP

commit: a63b40bd10446abbc9947810a3c10946194b0232
author: ritmun
SDCICD-1592 set progressive delivery e2e template to claim from cluster reserve

If no cluster reserve is found, cluster gets created as before

commit: 7295e9e30b7e9b7c98ac19cc69afb9b21c90ae8f
author: Josh Branham
Add support for running tests in a local container

commit: fe333fcd853a4de521fb7ad1d03fdfc0a8bf626b
author: Josh Branham
wip

commit: 0b49f10fd9004e1879e09f111e5f27d8b07cef4e
author: Josh Branham
Drop defunct tag-check.sh

commit: 2400affc32091b707df9f1d3045b049f0c11628c
author: Josh Branham
SREP-1170: Ensure `make pr-check` works on macOS and in Konflux (#580)

* Fix driver find for GNU vs BSD

* Fix temp dir creations

* Fix color output

* Don't limit checkout depth

* Wip: verbose clone

* Fix find

* Fix tag-check.sh

commit: c34457926b35123c1ad7a4f0a2fd65be162cdd8e
author: red-hat-konflux[bot]
chore(deps): update konflux references

Signed-off-by: red-hat-konflux <126015336+red-hat-konflux[bot]@users.noreply.github.com>

commit: 5871c28d6d42429695b1c6a6b4139e68a111a83f
author: red-hat-konflux[bot]
chore(deps): update registry.access.redhat.com/ubi8/ubi-minimal:latest docker digest to 5b195cf

Signed-off-by: red-hat-konflux <126015336+red-hat-konflux[bot]@users.noreply.github.com>

commit: d8e4ac2a57f42f34243ce12f4a857482eac5a0c4
author: Josh Branham
Add workspace support for integration test in Konflux

commit: f4234a5b5ddff5fef38d44b25f501b9f69c64a55
author: Josh Branham
Drop no longer needed .ci-operator.yaml config

commit: 29eb0e2ef6d1277ae57cd7de1255e0b3ec46143e
author: Josh Branham
SREP-1170: Create Tekton Pipeline to run `pr-check` in Konflux (#575)

* Wip: tekton pipeline to run pr-check test

* Fix workspace dir

* Fix tests

* Update PR CEL to include tests and conventions

commit: dbd5e9de0e2bca31287f903bc623a00ddaf1951f
author: Jim DAgostino
Add Jim DAgostino to team rocket alias

commit: 342cbf74301c57d13f71887be4a3095195b52787
author: red-hat-konflux[bot]
chore(deps): update konflux references

Signed-off-by: red-hat-konflux <126015336+red-hat-konflux[bot]@users.noreply.github.com>

commit: af91cc80aad89b339c163ea0369e132046cc3484
author: Brady Pratt
.tekton: add missing image-digest param

https://github.com/konflux-ci/build-definitions/blob/main/task/sast-unicode-check/0.3/MIGRATION.md#migration-from-02-to-03

Signed-off-by: Brady Pratt <bpratt@redhat.com>

commit: 6b3d4fabac7ea7744a674957ab0e80dad4d41ddd
author: Dakota Long
https://issues.redhat.com/browse/SREP-935

Update boilerplate to accept UBI versions 7-9 and not override to 8.

commit: a702fe7c75b8457f8f28d26983c0bf1296deb0e3
author: vkadapar
Add "CAD_PAGERDUTY_ROUTING_KEY" env variable to e2e bp template

commit: 62db42a8c1431cee50777cf0b6bbbcd893bbee44
author: Brady Pratt
update srep-infra-cicd team

Signed-off-by: Brady Pratt <bpratt@redhat.com>

commit: 8cf024558393575343d0578953ca6673015aa03e
author: Josh Branham
Cleanup make targets and fix LICENSE copy

commit: 5ed3ee399b4c9bcd9b0c6d9fb7f4d0e1f813d9ad
author: ritmun
SDCICD-1593 login to quay repo before push

commit: 5cb9efec537cd5618cfa2652df71f82f9368ba11
author: ritmun
SDCICD-1593 make e2e convention independent of operator convention

any repository can subscribe to this without operator bp

commit: c105a6d0dd30bc6973b3b7c669e16a86adab05f7
author: Brady Pratt
golang-osd-openshift-osde2e: add OWNERS file

Signed-off-by: Brady Pratt <bpratt@redhat.com>

commit: 1b42d876c286bfbbfef9efcb7b01ce331f7a9afa
author: Brady Pratt
golang-osd-operator-osde2e: rename template

Signed-off-by: Brady Pratt <bpratt@redhat.com>

commit: 9eb0f735cd9fe56fef2e83f9a7aadd798ae300bb
author: Claudio Busse
Add bergmannf to fuinctional leads

commit: 3165c4312253e34346723ef02267d8f1c5620b99
author: red-hat-konflux[bot]
chore(deps): update konflux references

Signed-off-by: red-hat-konflux <126015336+red-hat-konflux[bot]@users.noreply.github.com>

commit: 82a951c896e370238f74a0165f4ffd08f0f7b0b7
author: ritmun
rename "harness" to appropriate names

commit: d783fc073ade871568a6505d2331b98c1675518e
author: red-hat-konflux[bot]
chore(deps): update konflux references

Signed-off-by: red-hat-konflux <126015336+red-hat-konflux[bot]@users.noreply.github.com>

commit: 987b6b4eae42d8cd46543e2736d5780752a59bb0
author: Ravi Trivedi
Updating OWNERS_ALIASES for Hulk and Thor

commit: 5f60b4de09acb69aa8754ee56298e82497a33dae
author: ritmun
set ocm creds required to "false" during switchover from offline token to serviceaccount

OCM will still catch is creds are missing and report error, but this will allow both token based and SA based auths to work in the meantime

commit: 63e197978fa216a128a3264709229089008daf2b
author: Josh Branham
Stop forcing `GOOS=linux` in `go-build` target ~5 years ago this line was modified to enforce linux for building binaries.

This has the side effect of breaking `CGO` compilation on macOS. It can be fixed by
configuring a cross-sompiler that generates objects with Linux header files, however
when building on your _local_ machine (outside docker) there is no need to force this to linux.

When the binary is built inside a container, the `GOOS` will be set to linux.

commit: ff70614b063784d2247b9d907b7546a7ab296616
author: red-hat-konflux[bot]
chore(deps): update konflux references

Signed-off-by: red-hat-konflux <126015336+red-hat-konflux[bot]@users.noreply.github.com>

commit: 3483cfee75c27732506639bb2d572b93f1188da2
author: red-hat-konflux[bot]
chore(deps): update konflux references

Signed-off-by: red-hat-konflux <126015336+red-hat-konflux[bot]@users.noreply.github.com>

commit: 6a1a00a52830050c6437df54ca62408347c60632
author: Daniel Hall
Add myself to team Thor

commit: 0ada15b3227a6764786950f601a17e6a630d7a87
author: red-hat-konflux[bot]
chore(deps): update konflux references

Signed-off-by: red-hat-konflux <126015336+red-hat-konflux[bot]@users.noreply.github.com>

commit: c2c3c7bd292fdcd8d725cfd2de1c381da1b76141
author: Brady Pratt
SDCICD-1544: pipelines/catalog-builder: add prefetch-dependencies task

this is a requirement for the fbc-fips-check task

Signed-off-by: Brady Pratt <bpratt@redhat.com>

commit: 3acca82cd83cb16976135a7acab63124106ea84f
author: Brady Pratt
SDCICD-1552: .github/renovate.json: auto merge tekton changes

attempt to automerge tekton changes to reduce maintaince toil

Signed-off-by: Brady Pratt <bpratt@redhat.com>

commit: 55b20866f29e7bde67c3c1dfc8ea40d1834a8b57
author: Josh Branham
Trim whitespace in `OWNERS_ALIASES`

commit: e3b5e55b2e81028c03d842cddec79f03981f2f33
author: Brady Pratt
pipelines/catalog-builder: Add fbc-fips-check task

Signed-off-by: Brady Pratt <bpratt@redhat.com>

commit: 405840fcd4071d51c3d26524c94e96384b3490e5
author: red-hat-konflux[bot]
chore(deps): update konflux references

Signed-off-by: red-hat-konflux <126015336+red-hat-konflux[bot]@users.noreply.github.com>

commit: 1d2556fa0519114bb1fae25c67cd91eb7a159553
author: Brady Pratt
SDCICD-1542: fix invalid image ref

not sure why this is pointing to the buildah task

Signed-off-by: Brady Pratt <bpratt@redhat.com>

commit: fc1669b38d295a02df4610d8e99ddb2f1be0af18
author: Brady Pratt
pipelines/bundle-builder: add missing tasks

add sast-shell-check and sast-unicode-check, they are required

Signed-off-by: Brady Pratt <bpratt@redhat.com>

commit: 391ef5cbcbaffe25f4648cd1a8b7fd92a41ffcaa
author: Josh Branham
Update Konflux release process Update our documentation for how to make a new Konflux release. This primarily takes into account a race condition where updating a `ReleasePlanAdmission` tag does not reflect in the Konflux cluster for some time while ArgoCD syncs it.

commit: e5715ee3b67b45ca85e0fc0229676d837aaac4bb
author: Abhishek Abhishek
bump controller-gen version to v0.16.4

commit: 04a72d2f8aec83ac0456436ab0bbb7dfa597322e
author: red-hat-konflux[bot]
chore(deps): update konflux references

Signed-off-by: red-hat-konflux <126015336+red-hat-konflux[bot]@users.noreply.github.com>

commit: 2ede67fcf791c7edc5e5c10ef7dd8d6c998d6f0a
author: Amarthya Valija
OSD-28963: Preserve consumer dependabot.yml by appending boilerplate-managed section

commit: 1bdcc414deac935ac1ec2a70e1b604ad56a49515
author: konflux
Konflux build pipeline service account migration for image

Signed-off-by: konflux <konflux@no-reply.konflux-ci.dev>

commit: d858440bf1adf5901d37f58b48cf4561f3dc9df1
author: Claudio Busse
Maintain owner aliases

commit: 25ebf84467a78315ba3d8ab8bb2a8d68f15ca032
author: red-hat-konflux[bot]
chore(deps): update konflux references

Signed-off-by: red-hat-konflux <126015336+red-hat-konflux[bot]@users.noreply.github.com>

commit: d4c70344231da1a52fdbff09f58e2cb773a9466e
author: Josh Branham
Update OWNERS

Co-authored-by: Dustin Row <dustinrow@gmail.com>

commit: 66d6362651446b0dc1a12318482dcd1c9793d438
author: Chris Collins
Update OWNERS file

Updates OWNERS to use OWNERS_ALIASES, add team aurora as reviewers,
functional leads to approvers and maintainers, and Josh to maintainers.

Signed-off-by: Chris Collins <collins.christopher@gmail.com>

commit: 1c86242c815c092c357b16aac0e775a269d1bf9a
author: Josh Branham
Only copy /var/lib/jenkins/.docker/config.json if it exists, reducing distracting error output locally

commit: 470b67b55a473902f47425dcdc1e96e52368d954
author: Josh Branham
Fix usage of `PWD` for `op-generate` target in `goland-osd-operator` The `make op-generate` target was relying on `PWD` being set to know where the writeable local checkout was.

That was mistakingly removed in https://github.com/openshift/boilerplate/commit/3bd17ad71e5b6f8268a1ef499128f78ec99f675c

Adding back in essentially the same, although using `$(shell pwd)` explicilty when needed versus
setting the var for the whole Makefile.

commit: 7adce5c577cb75f1a4a64c8c4087dc0cf1f5f7ea
author: ritmun
Add readme to e2e scaffolding; Update osde2e convention readme

commit: 34ec9c27c09797ed4d067c199c389ee7a65669f8
author: Josh Branham
Clean up job output when running 'ensure.sh' This script had `set -x` set which was making a ton of noise in jobs. Updated them to use the env var we have in case you ever want to see full shell output.

commit: 84124f7d4bed3bad80a9998f87552c02b0c3c4f5
author: red-hat-konflux[bot]
chore(deps): update konflux references

Signed-off-by: red-hat-konflux <126015336+red-hat-konflux[bot]@users.noreply.github.com>

commit: 2de3d31033989d0137262f7a7ebbed8a20eb041f
author: ritmun
skip must-gather and destroy cluster steps in operator e2e suite

commit: 1e5a1b23c6019f79847f54e4f697d44b734faa73
author: Josh Branham
Set XDG_CACHE_HOME to avoid hackery with GOCACHE

commit: 56b55bd731db69c202d8ad95e54264ba497a2fd1
author: Josh Branham
Utilize custom `GOCACHE` for `op-generate` target In the `op-generate` target we call `controller-gen` which relies on the given modules modules to be installed. This suffers from the same issue where `GOCACHE` not being writeable is an issue.

This just plumbs `GOENV` through like we have done in previous PRs.

Tested this locally with the following diff on `aws-vpce-operator`, which was failing
a BP bump in https://github.com/openshift/aws-vpce-operator/pull/295

```diff
diff --git a/boilerplate/openshift/golang-osd-operator/standard.mk b/boilerplate/openshift/golang-osd-operator/standard.mk
index 576a954..b1a2d82 100644
--- a/boilerplate/openshift/golang-osd-operator/standard.mk
+++ b/boilerplate/openshift/golang-osd-operator/standard.mk
@@ -220,8 +220,8 @@ YQ = yq
 .PHONY: op-generate
 ## CRD v1beta1 is no longer supported.
 op-generate:
-       cd ./api; $(CONTROLLER_GEN) crd:crdVersions=v1,generateEmbeddedObjectMeta=true paths=./... output:dir=$(PWD)/deploy/crds
-       cd ./api; $(CONTROLLER_GEN) object paths=./...
+       cd ./api; ${GOENV} $(CONTROLLER_GEN) crd:crdVersions=v1,generateEmbeddedObjectMeta=true paths=./... output:dir=$(PWD)/deploy/crds
+       cd ./api; ${GOENV} $(CONTROLLER_GEN) object paths=./...

 .PHONY: openapi-generate
 openapi-generate:
```

Ran `make container-validate` which failed on me having the above diff from `boilerplate:master`, however then when running
`make op-generate` manually in the container it now passes and uses the custom cache.

commit: 4e454c98b0b3bf9c7cdbe118310bb8991f2e4287
author: Josh Branham
Remove the `GOLANGCI_OPTIONAL_CONFIG` option, which is unused In https://github.com/openshift/boilerplate/pull/92 we added an option to be able to pass a custom golangci-lint configuration on a per repo. I believe the intent is to have it be _additive_, in that it would run a second `golangci-lint` invocation with your custom config. This would only work if you added a linter, as removing one in this file still meant the original invocation would have failed with the boilerplate-based config.

Additionally, the gate that was designed to prevent `golangci-lint` from running a second time, unless `GOLANGCI_OPTIONAL_CONFIG` is set, appears to not be working, so we are currently running linting twice on all our repos.

Lastly, after doing a quick search of GitHub, it appears we only have to repos with the configuration:
- https://github.com/openshift/osd-metrics-exporter/ configures it but the file was previously deleted, so no-ops
- https://github.com/openshift/osd-cluster-ready configures it, but the file just enables `gosec` that is part of our base config

For the above reasons, this PR proposes removing this feature to simplify linting versus fixing bugs with the existing, unused process.

commit: ea756dfeb49a3482202d3b2eba438b9e7c0215c0
author: Diego Santamaria
SDE-4270 Switch OSDe2e to use OCM Client Credentials